In [74]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Прочитайте файл 2017_jun_final.csv за допомогою методу read_csv
# Прочитайте отриману таблицю, використовуючи метод head

jun2017 = pd.read_csv('2017_jun_final.csv')
print(jun2017.head())

   N                    Посада Мова програмування Спеціалізація  \
0  1        Junior QA engineer                NaN     Manual QA
1  2        Junior QA engineer                NaN     Manual QA
2  3         Software Engineer            C#/.NET           NaN
3  4         Software Engineer         JavaScript           NaN
4  5  Senior Software Engineer         JavaScript           NaN

  Загальний досвід роботи Досвід роботи на поточному місці  \
0                     0.5                              0.5
1         менше 3 місяців                  менше 3 місяців
2                       4                                1
3                       5                                4
4       10 і більше років                              0.5

   Зарплата на місяць  Зміна зарплати за 12 місяців   Місто   Розмір компанії  \
0                 400                             0  Харків        до 10 осіб
1                 430                           130  Харків  більше 1000 осіб
2                2500                           800    Київ      до 1000 осіб
3                2000                           400   Одеса       до 200 осіб
4                4500                           500    Інше        до 10 осіб

   ... Ще студент                    Рівень англійської  \
0  ...       True    Pre-intermediate (нище середнього)
1  ...       True  Upper-Intermediate (вище середнього)
2  ...      False               Intermediate (середній)
3  ...      False    Pre-intermediate (нище середнього)
4  ...      False               Intermediate (середній)

                   Предметна область      Дата заповнення  \
0                      iOS,eCommerce  12/06/2017 12:38:08
1                       Веб-розробка  12/06/2017 12:42:51
2  Веб-розробка,Корпоративні системи  12/06/2017 13:02:47
3  Desktop Applications,Веб-розробка  12/06/2017 13:03:01
4  Desktop Applications,Веб-розробка  12/06/2017 13:03:47

                                          User.Agent   exp current_job_exp  \
0  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...   0.5             0.5
1  Mozilla/5.0 (iPad; CPU OS 10_2_1 like Mac OS X...   0.0             0.0
2  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...   4.0             1.0
3  Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...   5.0             4.0
4  Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like...  10.0             0.5

  salary Валюта  cls
0    400    NaN   QA
1    430    NaN   QA
2   2500    NaN  DEV
3   2000    NaN  DEV
4   4500    NaN  DEV

[5 rows x 25 columns]

In [75]:
# Визначте розмір таблиці за допомогою методу shape

print(f"Number of rows {jun2017.shape[0]} and columns {jun2017.shape[1]}")

Number of rows 8704 and columns 25

In [76]:
# Визначте типи всіх стовпців за допомогою dataframe.dtypes

jun2017.dtypes

N                                     int64
Посада                               object
Мова програмування                   object
Спеціалізація                        object
Загальний досвід роботи              object
Досвід роботи на поточному місці     object
Зарплата на місяць                    int64
Зміна зарплати за 12 місяців          int64
Місто                                object
Розмір компанії                      object
Тип компанії                         object
Стать                                object
Вік                                   int64
Освіта                               object
Університет                          object
Ще студент                             bool
Рівень англійської                   object
Предметна область                    object
Дата заповнення                      object
User.Agent                           object
exp                                 float64
current_job_exp                     float64
salary                                int64
Валюта                               object
cls                                  object
dtype: object

In [77]:
# Порахуйте, яка частка пропусків міститься в кожній колонці (використовуйте методи isnull та sum)

jun2017.isnull().sum()

N                                      0
Посада                                 0
Мова програмування                  3850
Спеціалізація                       7219
Загальний досвід роботи                0
Досвід роботи на поточному місці       0
Зарплата на місяць                     0
Зміна зарплати за 12 місяців           0
Місто                                  0
Розмір компанії                        0
Тип компанії                           0
Стать                                  0
Вік                                    0
Освіта                                 0
Університет                          358
Ще студент                             0
Рівень англійської                     0
Предметна область                    223
Дата заповнення                        0
User.Agent                             0
exp                                    0
current_job_exp                        0
salary                                 0
Валюта                              8694
cls                                 1574
dtype: int64

In [78]:
# Видаліть усі стовпці з пропусками, крім стовпця "Мова програмування"
# Знову порахуйте, яка частка пропусків міститься в кожній колонці і 
# переконайтеся, що залишився тільки стовпець "Мова.програмування"

new_jun2017 = jun2017.dropna(axis=1, how='any').combine_first(jun2017[["Мова програмування"]])

new_jun2017.isnull().sum()

N                                      0
User.Agent                             0
current_job_exp                        0
exp                                    0
salary                                 0
Вік                                    0
Дата заповнення                        0
Досвід роботи на поточному місці       0
Загальний досвід роботи                0
Зарплата на місяць                     0
Зміна зарплати за 12 місяців           0
Мова програмування                  3850
Місто                                  0
Освіта                                 0
Посада                                 0
Розмір компанії                        0
Рівень англійської                     0
Стать                                  0
Тип компанії                           0
Ще студент                             0
dtype: int64

In [79]:
# Видаліть усі рядки у вихідній таблиці за допомогою методу dropna
# Визначте новий розмір таблиці за допомогою методу shape

new2_jun2017 = jun2017.dropna(axis=1, how='any')
print(f"Number of rows {new2_jun2017.shape[0]} and columns {new2_jun2017.shape[1]}")

Number of rows 8704 and columns 19

In [112]:
# Створіть нову таблицю python_data, в якій будуть тільки рядки зі спеціалістами, які вказали мову програмування Python
# Визначте розмір таблиці python_data за допомогою методу shape

python_data = jun2017.loc[jun2017['Мова програмування'] == 'Python']
print(f"Number of rows {python_data.shape[0]} and columns {python_data.shape[1]}")

Number of rows 207 and columns 25

In [125]:
# Використовуючи метод groupby, виконайте групування за стовпчиком "Посада"

result = python_data.groupby(by=['Посада'])
result.head()

,N,Посада,Мова програмування,Спеціалізація,Загальний досвід роботи,Досвід роботи на поточному місці,Зарплата на місяць,Зміна зарплати за 12 місяців,Місто,Розмір компанії,...,Ще студент,Рівень англійської,Предметна область,Дата заповнення,User.Agent,exp,current_job_exp,salary,Валюта,cls
12,13,Software Engineer,Python,NaN,1,менше 3 місяців,800,200,Київ,до 50 осіб,...,False,Pre-intermediate (нище середнього),"Веб-розробка,Інше",12/06/2017 13:05:54,Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...,1.00,0.00,800,NaN,DEV
68,69,Software Engineer,Python,NaN,1.5,0.5,900,900,Київ,до 10 осіб,...,True,Upper-Intermediate (вище середнього),Веб-розробка,12/06/2017 13:11:17,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,1.50,0.50,900,NaN,DEV
87,88,Junior Software Engineer,Python,NaN,0.5,0.5,600,0,Київ,до 10 осіб,...,True,Upper-Intermediate (вище середнього),"Веб-розробка,eCommerce",12/06/2017 13:12:25,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,0.50,0.50,600,NaN,DEV
114,115,Junior Software Engineer,Python,NaN,1.5,0.5,685,250,Київ,до 1000 осіб,...,False,Intermediate (середній),Інше,12/06/2017 13:14:52,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,1.50,0.50,685,NaN,DEV
143,144,Junior Software Engineer,Python,NaN,1,1,750,250,Київ,до 10 осіб,...,True,Upper-Intermediate (вище середнього),Веб-розробка,12/06/2017 13:19:10,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,1.00,1.00,750,NaN,DEV
153,154,Software Engineer,Python,NaN,2,1,1200,0,Дніпро,до 50 осіб,...,False,Advanced (просунутий),"Веб-розробка,Мультимедіа",12/06/2017 13:20:15,Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebK...,2.00,1.00,1200,NaN,DEV
162,163,Junior Software Engineer,Python,NaN,0.5,0.5,500,0,Вінниця,до 200 осіб,...,True,Pre-intermediate (нище середнього),Веб-розробка,12/06/2017 13:21:08,Mozilla/5.0 (Linux; Android 7.1.2; LG-D802 Bui...,0.50,0.50,500,NaN,DEV
171,172,Junior Software Engineer,Python,NaN,0.25,0.25,800,0,Київ,до 50 осіб,...,False,Advanced (просунутий),Телекомунікації,12/06/2017 13:22:31,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,0.25,0.25,800,NaN,DEV
217,218,Software Engineer,Python,NaN,8,2,2900,150,Львів,до 1000 осіб,...,False,Upper-Intermediate (вище середнього),"Веб-розробка,Корпоративні системи",12/06/2017 13:31:50,Mozilla/5.0 (Windows NT 6.2; Win64; x64) Apple...,8.00,2.00,2900,NaN,DEV
302,303,Senior Software Engineer,Python,NaN,10 і більше років,0.5,3500,-300,Київ,до 200 осіб,...,False,Upper-Intermediate (вище середнього),"Веб-розробка,Gamedev",12/06/2017 13:46:24,Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...,10.00,0.50,3500,NaN,DEV
373,374,Senior Software Engineer,Python,NaN,7,0.5,3100,1000,Дніпро,до 200 осіб,...,False,Upper-Intermediate (вище середнього),"Веб-розробка,Корпоративні системи",12/06/2017 13:58:16,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6...,7.00,0.50,3100,NaN,DEV
387,388,Software Engineer,Python,NaN,4,1.5,1200,0,Інше,до 10 осіб,...,False,Pre-intermediate (нище середнього),"Веб-розробка,eCommerce",12/06/2017 14:01:02,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,4.00,1.50,1200,NaN,DEV
1172,1173,Senior Software Engineer,Python,NaN,2,2,1300,800,Львів,до 50 осіб,...,True,Intermediate (середній),"Веб-розробка,Інше",12/06/2017 17:38:00,Mozilla/5.0 (Linux; Android 6.0.1; Redmi 3S Bu...,2.00,2.00,1300,NaN,DEV
1363,1364,Senior Software Engineer,Python,NaN,10 і більше років,2,1500,1000,Віддалено,до 10 осіб,...,False,Elementary (початковий),"Системне програмування,Корпоративні системи",12/06/2017 19:10:01,Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) ...,10.00,2.00,1500,NaN,DEV
1489,1490,Senior Software Engineer,Python,NaN,4,1,3300,430,Львів,до 1000 осіб,...,False,Upper-Intermediate (вище середнього),"Веб-розробка,Корпоративні системи",12/06/2017 20:48:17,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,4.00,1.00,3300,NaN,DEV
2632,2633,Technical Lead,Python,NaN,4,1.5,3500,1000,Київ,до 50 осіб,...,False,Upper-Intermediate (вище середнього),Веб-розробка,13/06/2017 12:37:02,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5...,4.00,1.50,3500,NaN,SDEV
3145,3146,Technical Lead,Python,NaN,10 і більше років,2,1425,475,Київ,до 50 осіб,...,False,Upper-Intermediate (вище середнього),Корпоративні системи,13/06/2017 14:51:19,Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52....,10.00,2.00,1425,NaN,SDEV
3935,3936,Technical Lead,Python,NaN,10 і більше років,0.25,3700,0,Київ,більше 1000 осіб,...,False,Upper-Intermediate (вище середнього),"Embedded,Інше",14/06/2017 12:26:36,Mozilla/5.0 (Linux; Android 5.0; SM-N900V Buil...,10.00,0.25,3700,NaN,SDEV
4323,4324,Technical Lead,Python,NaN,2,2,3300,800,Харків,до 200 осіб,...,False,Intermediate (середній),Веб-розробка,15/06/2017 11:16:57,Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53....,2.00,2.00,3300,NaN,SDEV
4746,4747,Technical Lead,Python,NaN,5,3,2900,180,Дніпро,до 10 осіб,...,False,Upper-Intermediate (вище середнього),Веб-розробка,16/06/2017 21:46:04,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2...,5.00,3.00,2900,NaN,SDEV
5748,5749,System Architect,Python,NaN,10 і більше років,0.25,3000,0,Київ,до 50 осіб,...,False,Upper-Intermediate (вище середнього),"Веб-розробка,eCommerce",20/06/2017 18:40:40,Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53....,10.00,0.25,3000,NaN,SDEV
8228,8229,System Architect,Python,NaN,10 і більше років,2,5000,0,Київ,до 10 осіб,...,False,Intermediate (середній),"Веб-розробка,Інше",06/07/2017 19:15:05,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4...,10.00,2.00,5000,NaN,SDEV

In [137]:
# Створіть новий DataFrame, де для згрупованих даних за стовпчиком "Посада", 
# виконайте агрегацію даних за допомогою методу agg і знайдіть мінімальне
# та максимальне значення у стовпчику "Зарплата.в.місяць"

new_python_data = python_data.groupby(by=['Посада'])
min_max_python_data = new_python_data.agg({'Зарплата на місяць' : ['min', 'max']})
print(min_max_python_data)

                         Зарплата на місяць
                                        min   max
Посада
Junior Software Engineer                100  1250
Senior Software Engineer               1300  9200
Software Engineer                       500  5400
System Architect                       3000  5000
Technical Lead                         1425  6200

In [181]:
# Створіть функцію fill_avg_salary, яка повертатиме середнє
# значення заробітної плати на місяць. Використовуйте її для
# методу apply та створіть новий стовпчик "avg"

def fill_avg_salary(args):
    res = args["Зарплата на місяць"].mean()
    return res

min_max_python_data['avg'] = min_max_python_data.apply(fill_avg_salary, axis=1)
min_max_python_data.head()

                         Зарплата на місяць           avg
                                        min   max
Посада
Junior Software Engineer                100  1250   675.0
Senior Software Engineer               1300  9200  5250.0
Software Engineer                       500  5400  2950.0
System Architect                       3000  5000  4000.0
Technical Lead                         1425  6200  3812.5

In [176]:
# Створіть описову статистику за допомогою
# методу describe для нового стовпчика.

min_max_python_data.describe()

      Зарплата на місяць                       avg
                     min          max
count           5.000000     5.000000     5.000000
mean         1265.000000  5410.000000  3337.500000
std          1115.739665  2848.771665  1700.091909
min           100.000000  1250.000000   675.000000
25%           500.000000  5000.000000  2950.000000
50%          1300.000000  5400.000000  3812.500000
75%          1425.000000  6200.000000  4000.000000
max          3000.000000  9200.000000  5250.000000

In [188]:
# Збережіть отриману таблицю в CSV файл
min_max_python_data.to_csv("salary_average.csv",sep=';', index=False, encoding='cp1251')